# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/mcjoin"
      description: "mcjoin | tiny multicast testing tool"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make clean all"
    branch_pattern: master

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --prefix=
  - make clean
  - make -j5
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/bin/mcjoin
  - size ~/tmp/bin/mcjoin
  - ~/tmp/bin/mcjoin -h
