# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MvcjsKSUPikcLKIYuLgVbEFBngeUnYG4khXnEVBRNrTdldfEMmy4OJaHQ9rdAHiJXobiR/KGCZXJh1CyG33k22+pCezgs5cidIKrHVEuTNz4Wv+5P/q7w8qtXtPqn88KsM0nJjDiAv6/AHfnp0+CbiW2vhG3M2uz8GLqXeBWHATC1YP1zOIqWAkjTxmAlKC9v4XFGEcLpfyXP4ym/WKWkegF4hC0G/tFL+mrGeg+7q/fHvMYujciR5czUQNOlVaWC8lhC0vGxuxtxGgZYQCzgMWjakVzXZTcuB0LvrdeycKPoKBP/AO4gX2lVxdLp03v7eErvAHymNqeNBApfpPqe0PPtrwhnAZMbJ9lfimCh+TWBfcEGdz7KpCZzwUPhPZ5krYisw3XHmbx/+iuvZ2SvZlakXYuP0nJtot1WyjUy9C/0yopZAYfk9s7DasZc/+O1gbKDoTrZEWe+rhYo4i1rjzqyMjhWeLOoIQX4gA3aLzEb0Vmi+67VD1M9NvDwtcuYRX5jM45rZ0JRPx5UGVMGmMwnJo7fsAA+JmJMo+94auN0jVfTAcxmHBHmushpkF+Jg8JUKkQ9rjRZGHAwkaVlicRbpEGMNh9Bu0VCkNVGzQKedWDv9WlwdoFe2YHhXOrbg5WfBRzWzp1clYaqwBhRFjwHmez/75Grt5TUAXCMBE="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/mcjoin"
      description: "mcjoin | tiny multicast testing tool"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make clean all"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure --prefix=
  - make clean
  - make -j5
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/bin/mcjoin
  - size ~/tmp/bin/mcjoin
  - ~/tmp/bin/mcjoin -h
